# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainForm.ui'
#
# Created by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainForm(object):
    def setupUi(self, MainForm):
        MainForm.setObjectName("MainForm")
        MainForm.setEnabled(True)
        MainForm.resize(1890, 902)
        MainForm.setMinimumSize(QtCore.QSize(901, 697))
        MainForm.setMaximumSize(QtCore.QSize(1890, 902))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/CNBC_Program.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainForm.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainForm)
        self.centralwidget.setObjectName("centralwidget")
        self.frameSearch = QtWidgets.QFrame(self.centralwidget)
        self.frameSearch.setGeometry(QtCore.QRect(0, 10, 1861, 51))
        self.frameSearch.setStyleSheet("QGroupBox {border 2px solid gay}")
        self.frameSearch.setFrameShape(QtWidgets.QFrame.Panel)
        self.frameSearch.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frameSearch.setLineWidth(1)
        self.frameSearch.setObjectName("frameSearch")
        self.radioAll = QtWidgets.QRadioButton(self.frameSearch)
        self.radioAll.setGeometry(QtCore.QRect(20, 10, 45, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans [unknown]")
        font.setPointSize(11)
        self.radioAll.setFont(font)
        self.radioAll.setChecked(True)
        self.radioAll.setObjectName("radioAll")
        self.radioActive = QtWidgets.QRadioButton(self.frameSearch)
        self.radioActive.setGeometry(QtCore.QRect(110, 10, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans [unknown]")
        font.setPointSize(11)
        self.radioActive.setFont(font)
        self.radioActive.setObjectName("radioActive")
        self.radioInActive = QtWidgets.QRadioButton(self.frameSearch)
        self.radioInActive.setGeometry(QtCore.QRect(210, 10, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans [unknown]")
        font.setPointSize(11)
        self.radioInActive.setFont(font)
        self.radioInActive.setObjectName("radioInActive")
        self.labelTraders = QtWidgets.QLabel(self.frameSearch)
        self.labelTraders.setGeometry(QtCore.QRect(360, 10, 48, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans [unknown]")
        font.setPointSize(11)
        self.labelTraders.setFont(font)
        self.labelTraders.setObjectName("labelTraders")
        self.comboTraders = QtWidgets.QComboBox(self.frameSearch)
        self.comboTraders.setGeometry(QtCore.QRect(420, 10, 191, 31))
        self.comboTraders.setObjectName("comboTraders")
        self.labelSearch = QtWidgets.QLabel(self.frameSearch)
        self.labelSearch.setGeometry(QtCore.QRect(690, 10, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans [unknown]")
        font.setPointSize(11)
        self.labelSearch.setFont(font)
        self.labelSearch.setObjectName("labelSearch")
        self.lineEditSearch = QtWidgets.QLineEdit(self.frameSearch)
        self.lineEditSearch.setGeometry(QtCore.QRect(780, 14, 161, 27))
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.pushButton = QtWidgets.QPushButton(self.frameSearch)
        self.pushButton.setGeometry(QtCore.QRect(960, 14, 44, 34))
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/Search_Icon_32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setObjectName("pushButton")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(20, 70, 1861, 771))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.treeViewShows = QtWidgets.QTreeView(self.splitter_2)
        self.treeViewShows.setToolTip("")
        self.treeViewShows.setToolTipDuration(5)
        self.treeViewShows.setObjectName("treeViewShows")
        self.splitter = QtWidgets.QSplitter(self.splitter_2)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.textEditShow = QtWidgets.QTextEdit(self.splitter)
        self.textEditShow.setObjectName("textEditShow")
        self.textEditShowNotes = QtWidgets.QTextEdit(self.splitter)
        self.textEditShowNotes.setObjectName("textEditShowNotes")
        MainForm.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainForm)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1890, 27))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        self.menu_About = QtWidgets.QMenu(self.menubar)
        self.menu_About.setObjectName("menu_About")
        self.menuShows = QtWidgets.QMenu(self.menubar)
        self.menuShows.setObjectName("menuShows")
        MainForm.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainForm)
        self.statusbar.setObjectName("statusbar")
        MainForm.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainForm)
        self.toolBar.setObjectName("toolBar")
        MainForm.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionExit = QtWidgets.QAction(MainForm)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon2)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout_CNBC = QtWidgets.QAction(MainForm)
        self.actionAbout_CNBC.setObjectName("actionAbout_CNBC")
        self.actionAdd_Show = QtWidgets.QAction(MainForm)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/TV_Shows_Icon_32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd_Show.setIcon(icon3)
        self.actionAdd_Show.setObjectName("actionAdd_Show")
        self.menu_File.addSeparator()
        self.menu_File.addAction(self.actionExit)
        self.menu_About.addAction(self.actionAbout_CNBC)
        self.menuShows.addAction(self.actionAdd_Show)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menuShows.menuAction())
        self.menubar.addAction(self.menu_About.menuAction())
        self.toolBar.addAction(self.actionExit)
        self.toolBar.addAction(self.actionAdd_Show)
        self.toolBar.addSeparator()

        self.retranslateUi(MainForm)
        self.actionExit.triggered.connect(MainForm.close)
        QtCore.QMetaObject.connectSlotsByName(MainForm)

    def retranslateUi(self, MainForm):
        _translate = QtCore.QCoreApplication.translate
        MainForm.setWindowTitle(_translate("MainForm", "CNBC Analysis"))
        self.frameSearch.setStatusTip(_translate("MainForm", "Search Criteria"))
        self.radioAll.setStatusTip(_translate("MainForm", "Search All Options (Active and In-active)"))
        self.radioAll.setText(_translate("MainForm", "All"))
        self.radioActive.setStatusTip(_translate("MainForm", "Search only options prior to Expiration Date"))
        self.radioActive.setText(_translate("MainForm", "Active"))
        self.radioInActive.setStatusTip(_translate("MainForm", "Search only options past the Expiration date"))
        self.radioInActive.setText(_translate("MainForm", "In-Active"))
        self.labelTraders.setText(_translate("MainForm", "Traders:"))
        self.labelSearch.setText(_translate("MainForm", "Search:"))
        self.treeViewShows.setStatusTip(_translate("MainForm", "Shows that have been entered and available for searching"))
        self.textEditShow.setStatusTip(_translate("MainForm", "Show notes"))
        self.textEditShowNotes.setStatusTip(_translate("MainForm", "Show notes - generally analyis info"))
        self.menu_File.setTitle(_translate("MainForm", "&File"))
        self.menu_About.setTitle(_translate("MainForm", "&Help"))
        self.menuShows.setTitle(_translate("MainForm", "Shows"))
        self.toolBar.setWindowTitle(_translate("MainForm", "toolBar"))
        self.actionExit.setText(_translate("MainForm", "E&xit"))
        self.actionExit.setStatusTip(_translate("MainForm", "Exit CNBC Program"))
        self.actionAbout_CNBC.setText(_translate("MainForm", "About CNBC"))
        self.actionAdd_Show.setText(_translate("MainForm", "Add Show"))
        self.actionAdd_Show.setToolTip(_translate("MainForm", "Add a Show"))
        self.actionAdd_Show.setStatusTip(_translate("MainForm", "Add a show to the CNBC Program"))

import Resources
