# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newShowForm.ui'
#
# Created by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_newShowDialog(object):
    def setupUi(self, newShowDialog):
        newShowDialog.setObjectName("newShowDialog")
        newShowDialog.resize(1074, 832)
        self.label = QtWidgets.QLabel(newShowDialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 91, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(newShowDialog)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 71, 17))
        self.label_2.setObjectName("label_2")
        self.dateEditCreatedDate = QtWidgets.QDateEdit(newShowDialog)
        self.dateEditCreatedDate.setGeometry(QtCore.QRect(110, 20, 110, 27))
        self.dateEditCreatedDate.setObjectName("dateEditCreatedDate")
        self.dateEditShowDate = QtWidgets.QDateEdit(newShowDialog)
        self.dateEditShowDate.setGeometry(QtCore.QRect(110, 50, 110, 27))
        self.dateEditShowDate.setObjectName("dateEditShowDate")
        self.groupBoxParticipants = QtWidgets.QGroupBox(newShowDialog)
        self.groupBoxParticipants.setGeometry(QtCore.QRect(50, 110, 491, 321))
        self.groupBoxParticipants.setObjectName("groupBoxParticipants")
        self.frameParticipants = QtWidgets.QFrame(self.groupBoxParticipants)
        self.frameParticipants.setGeometry(QtCore.QRect(0, 20, 491, 301))
        self.frameParticipants.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameParticipants.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frameParticipants.setLineWidth(2)
        self.frameParticipants.setObjectName("frameParticipants")
        self.comboBoxModerator = QtWidgets.QComboBox(self.frameParticipants)
        self.comboBoxModerator.setGeometry(QtCore.QRect(140, 10, 141, 33))
        self.comboBoxModerator.setObjectName("comboBoxModerator")
        self.comboBoxTrader1 = QtWidgets.QComboBox(self.frameParticipants)
        self.comboBoxTrader1.setGeometry(QtCore.QRect(210, 60, 141, 33))
        self.comboBoxTrader1.setObjectName("comboBoxTrader1")
        self.comboBoxTrader2 = QtWidgets.QComboBox(self.frameParticipants)
        self.comboBoxTrader2.setGeometry(QtCore.QRect(210, 100, 141, 33))
        self.comboBoxTrader2.setObjectName("comboBoxTrader2")
        self.comboBoxTrader3 = QtWidgets.QComboBox(self.frameParticipants)
        self.comboBoxTrader3.setGeometry(QtCore.QRect(210, 140, 141, 33))
        self.comboBoxTrader3.setObjectName("comboBoxTrader3")
        self.comboBoxTrader4 = QtWidgets.QComboBox(self.frameParticipants)
        self.comboBoxTrader4.setGeometry(QtCore.QRect(210, 180, 141, 33))
        self.comboBoxTrader4.setObjectName("comboBoxTrader4")
        self.comboBoxChartist = QtWidgets.QComboBox(self.frameParticipants)
        self.comboBoxChartist.setGeometry(QtCore.QRect(210, 220, 141, 33))
        self.comboBoxChartist.setObjectName("comboBoxChartist")
        self.label_3 = QtWidgets.QLabel(self.frameParticipants)
        self.label_3.setGeometry(QtCore.QRect(40, 20, 71, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans [unknown]")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frameParticipants)
        self.label_4.setGeometry(QtCore.QRect(110, 70, 71, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans [unknown]")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frameParticipants)
        self.label_5.setGeometry(QtCore.QRect(110, 110, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Noto Sans [unknown]")
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frameParticipants)
        self.label_6.setGeometry(QtCore.QRect(110, 150, 71, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans [unknown]")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frameParticipants)
        self.label_7.setGeometry(QtCore.QRect(110, 190, 71, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans [unknown]")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frameParticipants)
        self.label_8.setGeometry(QtCore.QRect(110, 230, 71, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans [unknown]")
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.comboBoxGuest = QtWidgets.QComboBox(self.frameParticipants)
        self.comboBoxGuest.setGeometry(QtCore.QRect(260, 260, 141, 33))
        self.comboBoxGuest.setObjectName("comboBoxGuest")
        self.label_9 = QtWidgets.QLabel(self.frameParticipants)
        self.label_9.setGeometry(QtCore.QRect(160, 270, 71, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans [unknown]")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.groupBox = QtWidgets.QGroupBox(newShowDialog)
        self.groupBox.setGeometry(QtCore.QRect(580, 110, 451, 321))
        self.groupBox.setObjectName("groupBox")
        self.frame = QtWidgets.QFrame(self.groupBox)
        self.frame.setGeometry(QtCore.QRect(0, 20, 451, 301))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(50, 60, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans [unknown]")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setGeometry(QtCore.QRect(50, 100, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans [unknown]")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(50, 140, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans [unknown]")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setGeometry(QtCore.QRect(50, 170, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans [unknown]")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(50, 220, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Noto Sans [unknown]")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.lineEdiSecurity1 = QtWidgets.QLineEdit(self.frame)
        self.lineEdiSecurity1.setGeometry(QtCore.QRect(150, 50, 71, 31))
        self.lineEdiSecurity1.setObjectName("lineEdiSecurity1")
        self.lineEdiSecurity2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdiSecurity2.setGeometry(QtCore.QRect(150, 90, 71, 31))
        self.lineEdiSecurity2.setObjectName("lineEdiSecurity2")
        self.lineEdiSecurity3 = QtWidgets.QLineEdit(self.frame)
        self.lineEdiSecurity3.setGeometry(QtCore.QRect(150, 130, 71, 31))
        self.lineEdiSecurity3.setObjectName("lineEdiSecurity3")
        self.lineEdiSecurity4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdiSecurity4.setGeometry(QtCore.QRect(150, 170, 71, 31))
        self.lineEdiSecurity4.setObjectName("lineEdiSecurity4")
        self.lineEdiSecurity5 = QtWidgets.QLineEdit(self.frame)
        self.lineEdiSecurity5.setGeometry(QtCore.QRect(150, 210, 71, 31))
        self.lineEdiSecurity5.setObjectName("lineEdiSecurity5")
        self.pushButtonPlay1 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPlay1.setGeometry(QtCore.QRect(240, 50, 85, 27))
        self.pushButtonPlay1.setObjectName("pushButtonPlay1")
        self.pushButtonPlay2 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPlay2.setGeometry(QtCore.QRect(240, 90, 85, 27))
        self.pushButtonPlay2.setObjectName("pushButtonPlay2")
        self.pushButtonPlay3 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPlay3.setGeometry(QtCore.QRect(240, 130, 85, 27))
        self.pushButtonPlay3.setObjectName("pushButtonPlay3")
        self.pushButtonPlay4 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPlay4.setGeometry(QtCore.QRect(240, 170, 85, 27))
        self.pushButtonPlay4.setObjectName("pushButtonPlay4")
        self.pushButtonPlay5 = QtWidgets.QPushButton(self.frame)
        self.pushButtonPlay5.setGeometry(QtCore.QRect(240, 210, 85, 27))
        self.pushButtonPlay5.setObjectName("pushButtonPlay5")
        self.checkBoxActive1 = QtWidgets.QCheckBox(self.frame)
        self.checkBoxActive1.setGeometry(QtCore.QRect(350, 50, 71, 22))
        self.checkBoxActive1.setObjectName("checkBoxActive1")
        self.checkBoxActive2 = QtWidgets.QCheckBox(self.frame)
        self.checkBoxActive2.setGeometry(QtCore.QRect(350, 90, 71, 22))
        self.checkBoxActive2.setObjectName("checkBoxActive2")
        self.checkBoxActive3 = QtWidgets.QCheckBox(self.frame)
        self.checkBoxActive3.setGeometry(QtCore.QRect(350, 130, 71, 22))
        self.checkBoxActive3.setObjectName("checkBoxActive3")
        self.checkBoxActive4 = QtWidgets.QCheckBox(self.frame)
        self.checkBoxActive4.setGeometry(QtCore.QRect(350, 170, 71, 22))
        self.checkBoxActive4.setObjectName("checkBoxActive4")
        self.checkBoxActive5 = QtWidgets.QCheckBox(self.frame)
        self.checkBoxActive5.setGeometry(QtCore.QRect(350, 210, 71, 22))
        self.checkBoxActive5.setObjectName("checkBoxActive5")
        self.pushButtonReset = QtWidgets.QPushButton(newShowDialog)
        self.pushButtonReset.setGeometry(QtCore.QRect(50, 720, 141, 51))
        self.pushButtonReset.setObjectName("pushButtonReset")
        self.pushButtonNoAdd = QtWidgets.QPushButton(newShowDialog)
        self.pushButtonNoAdd.setGeometry(QtCore.QRect(550, 730, 141, 51))
        self.pushButtonNoAdd.setObjectName("pushButtonNoAdd")
        self.pushButtonAdd = QtWidgets.QPushButton(newShowDialog)
        self.pushButtonAdd.setGeometry(QtCore.QRect(890, 730, 141, 51))
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.textEditShowNotes = QtWidgets.QTextEdit(newShowDialog)
        self.textEditShowNotes.setGeometry(QtCore.QRect(50, 470, 981, 221))
        self.textEditShowNotes.setObjectName("textEditShowNotes")
        self.label_15 = QtWidgets.QLabel(newShowDialog)
        self.label_15.setGeometry(QtCore.QRect(50, 450, 91, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans [unknown]")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(newShowDialog)
        self.label_16.setGeometry(QtCore.QRect(880, 10, 101, 101))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap(":/img/cnbc.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")

        self.retranslateUi(newShowDialog)
        QtCore.QMetaObject.connectSlotsByName(newShowDialog)

    def retranslateUi(self, newShowDialog):
        _translate = QtCore.QCoreApplication.translate
        newShowDialog.setWindowTitle(_translate("newShowDialog", "New Show"))
        self.label.setText(_translate("newShowDialog", "Created Date:"))
        self.label_2.setText(_translate("newShowDialog", "Show Date:"))
        self.groupBoxParticipants.setTitle(_translate("newShowDialog", "Participants"))
        self.label_3.setText(_translate("newShowDialog", "Moderator:"))
        self.label_4.setText(_translate("newShowDialog", "Trader 1:"))
        self.label_5.setText(_translate("newShowDialog", "Trader 2:"))
        self.label_6.setText(_translate("newShowDialog", "Trader 3:"))
        self.label_7.setText(_translate("newShowDialog", "Trader 4:"))
        self.label_8.setText(_translate("newShowDialog", "Chartist:"))
        self.label_9.setText(_translate("newShowDialog", "Guest:"))
        self.groupBox.setTitle(_translate("newShowDialog", "Securities Discussed:"))
        self.label_10.setText(_translate("newShowDialog", "Security 1:"))
        self.label_11.setText(_translate("newShowDialog", "Security 2:"))
        self.label_12.setText(_translate("newShowDialog", "Security 3:"))
        self.label_13.setText(_translate("newShowDialog", "Security 4:"))
        self.label_14.setText(_translate("newShowDialog", "Security 5:"))
        self.pushButtonPlay1.setText(_translate("newShowDialog", "The Play"))
        self.pushButtonPlay2.setText(_translate("newShowDialog", "The Play"))
        self.pushButtonPlay3.setText(_translate("newShowDialog", "The Play"))
        self.pushButtonPlay4.setText(_translate("newShowDialog", "The Play"))
        self.pushButtonPlay5.setText(_translate("newShowDialog", "The Play"))
        self.checkBoxActive1.setText(_translate("newShowDialog", "Active"))
        self.checkBoxActive2.setText(_translate("newShowDialog", "Active"))
        self.checkBoxActive3.setText(_translate("newShowDialog", "Active"))
        self.checkBoxActive4.setText(_translate("newShowDialog", "Active"))
        self.checkBoxActive5.setText(_translate("newShowDialog", "Active"))
        self.pushButtonReset.setText(_translate("newShowDialog", "Reset To Defaults"))
        self.pushButtonNoAdd.setText(_translate("newShowDialog", "Don\'t Add This Show"))
        self.pushButtonAdd.setText(_translate("newShowDialog", "Add This Show"))
        self.label_15.setText(_translate("newShowDialog", "Show Notes:"))

import Resources
